server:
  port: 8080
  servlet:
    context-path: /mall/
spring:
  application:
    name: mall
  profiles:
    active: dev  # 环境dev|test|pro
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    async:
      request-timeout: 20s
#日志配置
logging:
  file:
    path: /home/logs